### ISSUE TITLE
Missing file in data/

### ISSUE THREAD

**Issue by adomingues** [klevdiamanti/multitissue_ms_proteomics#1]
Hi @klevdiamanti,

first of all thank you for providing the code for the Mass-Spec analysis. I was trying to execute it but ran into an error:

```R
tmp.azpid <- unique.gene.id(azpid.index_ = dia$index$AZpID)
Error in file(file, "rt") : cannot open the connection
```

which ultimately comes from the file `gene.id.file <- "../data/gsea_files/all.gene.ids.txt"` not being present in the repo

https://github.com/klevdiamanti/multitissue_ms_proteomics/blob/main/R/ms_proteomics_pipeline.Rmd#L60

Could you please upload it? 

A unrelated question is that the sample names in `proteomics_random.xlsx` and `covars_random.xlsx` are named rand*  which is not the same format supplied in the supp matherials of the paper. Are these the same samples and are the intensity values those used in the papers?

Thank you!
António

**Comment by klevdiamanti** [comment]
Hi ,

Thanks for picking this up. Indeed the file you mentioned was missing, but it has been uploaded now. I have tested the rest of the pipeline and it seems to be working without any issues.

The datasets included in the repo are synthetic data that mimic the datasets included in the supplementary materials of the paper, and the format of the data is different. However, I think that with minimal data wrangling one may shape the data from the manuscript to run in the pipeline without problems.

Best,
Klev

**Comment by adomingues** [comment]
Thank you  @klevdiamanti!

Data wrangling shouldn't be a problem, but to make sure I pick the right data, can you please confirm if:

- sample data is that Table s1a
- protein intensity files are in Table s1c

it would be very appreciated. 

Best regards,
António

**Comment by klevdiamanti** [comment]
Yes, protein levels are in Table S1c and other viariables are in Table S1a.

Best,
Klev
